### ISSUE TITLE
aws_vpc resource raises exception when unsupported target has been specified

### ISSUE THREAD

**Issue by burtlo** [chef/inspec#2733]
### Description

The `aws_vpc` resource throws a stack trace instead of a message that the platform is unsupported.

### InSpec and Platform Version

InSpec 2.0.17 on Mac OSX 10.13.13

### Replication Case

I create a control for an `aws_ec2_instance`.

```ruby
describe aws_ec2_instance('i-0fe9dca242e64dc94') do
  it { should be_running }
  its('image_id') { should eq 'ami-d5d7ffae' }
  its('instance_type') { should eq 't1.micro' }
  its('vpc_id') { should eq 'vpc-4e904735' }
  its('subnet_id') { should eq 'subnet-170e3573' }
  its('security_group_ids') { should cmp ["sg-9f9b9ae8", "sg-d19c9da6"] }
end
```

I execute a scan without an AWS target. I receive a message that tells me that my platform is unsupported.

```shell
$ inspec exec training-aws-security

Profile: InSpec Profile (training-aws-security)
Version: 0.1.0
Target:  local://

  EC2 Instance
     ↺  Resource Aws_ec2_instance is not supported on platform mac_os_x/17.4.0.
```

I create a control for an `aws_vpc` resource.

```ruby
describe aws_vpc('vpc-4e904735') do
  its('state') { should eq 'available' }
  its('cidr_block') { should eq '10.0.0.0/16' }
end
```

I execute a scan without an AWS target. I receive a stack trace.

```
$ inspec exec training-aws-security
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/resources/aws/aws_vpc.rb:20:in `block (2 levels) in <class:AwsVpc>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/resources/aws/aws_vpc.rb:15:in `to_s'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:133:in `populate'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:258:in `create'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:421:in `set_it_up'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:385:in `subclass'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:259:in `block in define_example_group_method'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner_rspec.rb:27:in `example_group'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:304:in `rspec_skipped_block'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:265:in `get_check_example'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:281:in `block in register_rule'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:280:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:280:in `flat_map'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:280:in `register_rule'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:97:in `block in load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:96:in `each'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:96:in `load'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/runner.rb:103:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/inspec/cli.rb:168:in `exec'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/bin/inspec:12:in `<top (required)>'
	from /opt/inspec/bin/inspec:72:in `load'
	from /opt/inspec/bin/inspec:72:in `<main>'
```

**Comment by burtlo** [comment]
I am also seeing this same exception when I write a control with tests for a VPC that does not exist.

```
/opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/resources/aws/aws_vpc.rb:20:in `block (2 levels) in <class:AwsVpc>': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/inspec-2.0.17/lib/resources/aws/aws_vpc.rb:15:in `to_s'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:180:in `build_description_from'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:133:in `populate'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/metadata.rb:258:in `create'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:421:in `set_it_up'
	from /opt/inspec/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:385:in `subclass'
```

**Comment by burtlo** [comment]
The error in the `to_s` is likely because the instance variable used in the defined methods is using an object that is nil. https://github.com/chef/inspec/blob/master/lib/resources/aws/aws_vpc.rb#L20

**Comment by clintoncwolfe** [comment]
Thanks @burtlo for the great diagnosis - VPC was the first resource to use an "inner object" hash in an instance variable (and the last!).  We've just been delaying fixing that until we got around to it.

I edited the title of the issue - I think the simpler case is simply a search miss (or anything that would cause `to_s` to be called when `@vpc` is unpopulated).

**Comment by JohnVonNeumann** [comment]
This doesn't just occur when it can't find the vpc, I've found it's also occurring when no creds are provided. Which is a strange one.
